name: aws_s3_plugin_flutter
description: This package for uploading private file(s) to AWS S3 with upload percentage. also it is able to access the private files through presigned URLs which is the most basic thing of any mobile app with AWS private file system

version: 0.0.5
homepage: "https://github.com/mdavidkhan/aws_s3_plugin_flutter"

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: org.deetechpk.aws_s3_plugin_flutter
        pluginClass: AwsS3PluginFlutterPlugin
      ios:
        pluginClass: AwsS3PluginFlutterPlugin

